apiVersion: v1
kind: Secret
metadata:
  name: {{.Values.secrets.name}}
  namespace: kube-system

type: opaque
stringData:
  username: a2Fhcg==
  Key: Bmdsfdf565464565
  password: a2Fhcg==
  HF_TOKEN: "{{ .Values.hftoken }}"