name: CI Phase 1 - Basic Build

on:
  push:
    branches:
      - main

jobs:
  sonar:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Sonar Scan
      uses: SonarSource/sonarcloud-github-action@v2
      with:
        fetch-depth: 0
        args: >
          -Dsonar.projectKey=Kaarvannan_Pipeline-with-Github-actions
          -Dsonar.organization=kaarvannan
          -Dsonar.sources=.
          -Dsonar.python.version=3.10
  
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    - name: Quality Gate
      uses: SonarSource/sonarqube-quality-gate-action@v1
      timeout-minutes: 5
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  build:
    runs-on: ubuntu-latest
    needs: sonar
    outputs:
      image2: ${{ steps.set_repo.outputs.image }}

    permissions:
      id-token: write
      contents: read

    steps:
    - uses: actions/checkout@v4

    # - name: Configure AWS credentials
    #   uses: aws-actions/configure-aws-credentials@v4
    #   # with:
    #   #   aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #   #   aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    #   #   aws-region: us-east-1

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::990227773016:role/githubRole
        aws-region: us-east-1

    - name: Test ECR
      run: aws ecr describe-repositories


    - name: Login to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build, Tag and Push Image to ECR
      id: set_repo
      shell: bash
      run: |
        IMAGE_TAG=${GITHUB_SHA::9}
        ACCOUNT_ID=${{ secrets.AWS_ACCOUNT_ID }}
        REGION=us-east-1
        REPO_NAME=githubactions/dockerimage
    
        ECR_URI=$ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/$REPO_NAME
    
        docker build -t iris-app:$IMAGE_TAG .
        docker tag iris-app:$IMAGE_TAG $ECR_URI:$IMAGE_TAG
        docker push $ECR_URI:$IMAGE_TAG
    
        IMAGE_FULL="$ECR_URI:$IMAGE_TAG"
    
        echo "image=$IMAGE_FULL" >> $GITHUB_OUTPUT
    
        echo "DEBUG_IMAGE=$IMAGE_FULL"
    - name: Show step output
      run: echo "STEP=${{ steps.set_repo.outputs.image }}"

  deploy:
    runs-on: ubuntu-latest
    needs: build

    permissions:
      id-token: write
      contents: read

    steps:

    - uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::990227773016:role/githubRole
        aws-region: us-east-1

    - name: Test identity
      run: aws sts get-caller-identity

    - name: Test Eks
      run: aws eks describe-cluster --name Eks-cluster --region us-east-1
    - name: Update kubeconfig
      run: aws eks update-kubeconfig --name Eks-cluster --region us-east-1 
    - name: Test kubectl
      run: kubectl get nodes
    - name: Install Helm
      run: curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

    - name: Show all outputs
      run: echo '${{ toJson(needs.build.outputs) }}'

    - name: Image used in build job
      run: echo "Image used in build job is ${{ needs.build.outputs.image2 }}"

      
    - name: Deploy with Helm
      env:
        HF_TOKEN: ${{ secrets.HF_TOKEN }}
      run: helm upgrade --install iris-release ./second_Deployment --set image=${{ needs.build.outputs.image2 }} --set hftoken=${{ secrets.HF_TOKEN }} --wait --timeout 500s


